#!/bin/sh
# postrm script for todo
set -e

case "$1" in
    purge)
        rm -rf /var/lib/todo
        deluser --quiet --system todo 2>/dev/null || true
        delgroup --quiet --system todo 2>/dev/null || true
        rm -f /etc/default/todo
        ;;
esac

#DEBHELPER#
exit 0
